# Generated by Django 6.0.6 on 2026-06-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_office_is_records_office_alter_user_is_active_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comm_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('n/a', 'Not Applicable')], default='n/a', help_text='For letters and memos: is this between ASC offices (internal) or an outside org (external)?', max_length=10, verbose_name='Communication type'),
        ),
        migrations.AddField(
            model_name='document',
            name='confidentiality',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted')], default='internal', help_text='Public = anyone can view and download. Internal = ASC employees can view but not download. Restricted = Records Office only (e.g. complaints, grievances, personnel matters).', max_length=12),
        ),
        migrations.AddField(
            model_name='document',
            name='confidentiality_note',
            field=models.TextField(blank=True, help_text='Optional note explaining why this is restricted (not shown to employees).'),
        ),
        migrations.AlterField(
            model_name='document',
            name='destination_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_docs', to='accounts.office'),
        ),
    ]
