# Generated by Django 4.2.30 on 2026-07-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinglog',
            options={'default_permissions': ('view', 'add'), 'ordering': ['timestamp']},
        ),
    ]
