# Generated by Django 6.0.6 on 2026-06-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_records_office',
            field=models.BooleanField(default=False, help_text='Mark this if this is the Records Office — its members get admin access.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('records_admin', 'Records Office Admin'), ('employee', 'Employee (Read-Only)')], default='employee', max_length=20),
        ),
    ]
