# Generated by Django 6.0.6 on 2026-06-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_office_is_records_office_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='is_records_office',
            field=models.BooleanField(default=False, help_text='Mark this if this is the Records Office.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('records_officer', 'Records Officer'), ('program_chair', 'Program Chair'), ('faculty', 'Faculty')], default='faculty', max_length=20),
        ),
    ]
